  const [formData, setFormData] = useState({
    title: "",
    description: "",
    houseType: "",
    transactionType: "",
    province: "",
    city: "",
    district: "",
    streetAddress: "",
    landmark: "",
    bedrooms: "",
    bathrooms: "",
    area:0,
    floor:0,
    totalFloor:0,
    yearBuilt:0,
    furniture: "",
    parking: "",
    security: "",
    amenities: {
      parking: false,
      elevator: false,
      security: false,
      garden: false,
      pool: false,
      balcony: false,
      ac: false,
      heating: false,
      internet: false,
      cable_tv: false,
      pet_friendly: false,
      furnical: false,
    },
    amount: "",
    currency: "AFN",
    period: "",
    negotiable: false,
  });